runtime:
  cache_dir: ./.cache/antora

site:
  title: "Change me your title lives as site.title in ./zero-touch-site.yml"
  url: https://redhat-scholars.github.io/course-template
  # start_page: modules::index.adoc
  start_page: modules::module-01.adoc

content:
  sources:
    - url: ./
      start_path: content

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./content/lib/tab-block.js
    - ./content/lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/tonykay/demo-gpte-classroom-ui/raw/main/releases/download/v0.0.2/ui-bundle.zip
    # url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.2/bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./www