---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Module 1"
    - name: module-02
      label: "Module 2"
    - name: module-03
      label: "Module 3"

tabs:
  - name: ">_ terminal"
    type: "terminal"  # available types: terminal, double terminal
  - name: "Asciidoc Doc"
    url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
    external: true
