---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Module 1"
    - name: module-02
      label: "Module 2"
    - name: module-03
      label: "Podman ps"

tabs:
  - name: ">_ root"
    port: 443
    path: /wetty
    user: rhel
    host: bastion
