---
- name: Playbook for the ansible-runner API
  hosts: all
  gather_facts: false
  become: false
  vars:
    module_directory: index
    module_stage: setup

  tasks:
    - name: Simple debug task
      ansible.builtin.debug:
        msg: "Hello Runner"

    - name: Run {{ module_directory }}/{{ module_stage }}.sh on host
      ansible.builtin.script:
        cmd: "./{{ module_directory }}/{{ module_stage }}.sh"
      register: r_result

    - name: Output script result
      ansible.builtin.debug:
        var: r_result
